# Generated by Django 3.1.5 on 2021-01-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='value',
            field=models.CharField(default='0', max_length=244),
        ),
    ]
